const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  // ── 3 HÀM BẢO MẬT BẮT BUỘC PHẢI CÓ ────────────────────────────────────────
  getHWID:      ()         => ipcRenderer.invoke('auth:get-hwid'),
  checkLicense: ()         => ipcRenderer.invoke('auth:check-license'),
  activateApp:  (key)      => ipcRenderer.invoke('auth:activate', key),

  // ── VOICES / TTS (TÍNH NĂNG GIỌNG NÓI MỚI) ────────────────────────────────
  geminiTTS:        (data) => ipcRenderer.invoke('gemini:tts', data),
  geminiTTSSRT:     (data) => ipcRenderer.invoke('gemini:tts-srt', data),
  onGeminiSRTProgress: (cb) => ipcRenderer.on('gemini-srt-progress', (_e, data) => cb(data)),
  onGeminiSRTLog:      (cb) => ipcRenderer.on('gemini-srt-log', (_e, text) => cb(text)),
  getVoices:     ()     => ipcRenderer.invoke('tts:get-voices'),
  generateVoice:    (data) => ipcRenderer.invoke('tts:generate', data),
  generateSRTVoice: (data) => ipcRenderer.invoke('tts:generate-srt', data),
  elTTS_SRT:        (data) => ipcRenderer.invoke('elevenlabs:tts-srt', data),
  onTTSSRTProgress: (cb)   => ipcRenderer.on('tts-srt-progress', (_e, data) => cb(data)),
  onVoiceLog:       (cb)   => ipcRenderer.on('voice-log', (_e, data) => cb(data)),
  previewVoice:  (name) => ipcRenderer.invoke('tts:preview', name), // <--- DÒNG MỚI THÊM

  // ── VIDEO EDITOR (FFMPEG) ─────────────────────────────────────────────────
  cutVideo:        (data) => ipcRenderer.invoke('video:cut', data),
  onVideoLog:      (cb)   => ipcRenderer.on('video-log', (_e, data) => cb(data)),
  readVideoFolder: (path) => ipcRenderer.invoke('video:read-folder', path),
  mergeVideo:      (data) => ipcRenderer.invoke('video:merge', data),
  extractImages:   (data) => ipcRenderer.invoke('video:extract-images', data),
  burnSubtitles:   (data) => ipcRenderer.invoke('video:burnSubtitles', data),
  replaceAudio:    (data) => ipcRenderer.invoke('video:replaceAudio', data),
  mixAudio:        (data) => ipcRenderer.invoke('video:mixAudio', data),
  // ── VEO STUDIO ─────────────────────────────────────────────────
  runVeo:         (data) => ipcRenderer.invoke('veo:run', data),
  extendVideo:    (data) => ipcRenderer.invoke('veo:extend', data),
  extendChain:    (data) => ipcRenderer.invoke('veo:extend-chain', data),
  onVeoLog:       (cb)   => ipcRenderer.on('veo-log', (_e, data) => cb(data)),
  checkVeoCookie: (cookie) => ipcRenderer.invoke('veo:check-cookie', cookie),
  // ── CÁC HÀM CŨ ────────────────────────────────────────────────────────────
  getJobs:    ()         => ipcRenderer.invoke('db:get-jobs'),
  createJob:  (jobData)  => ipcRenderer.invoke('db:create-job', jobData),
  deleteJob:  (id)       => ipcRenderer.invoke('db:delete-job', id),
  retryJob:   (id)       => ipcRenderer.invoke('db:retry-job',  id),
  countJobs:  (status)   => ipcRenderer.invoke('db:count-jobs', status),
  getConcurrency:  ()        => ipcRenderer.invoke('settings:get-concurrency'),
  setConcurrency:  (value)   => ipcRenderer.invoke('settings:set-concurrency', value),
  getSetting:      (key, dv) => ipcRenderer.invoke('settings:get', key, dv),
  setSetting:      (key, v)  => ipcRenderer.invoke('settings:set', key, v),
  openBrowserLogin:  (profileId) => ipcRenderer.invoke('browser:open-login', profileId),
  checkLogin:        (profileId) => ipcRenderer.invoke('browser:check-login', profileId),
  checkAllLogins:    (ids)       => ipcRenderer.invoke('browser:check-all-logins', ids),
  closeBrowser:      ()          => ipcRenderer.invoke('browser:close'),
  selectFile:        (type)      => ipcRenderer.invoke('dialog:select-file', type),
  selectFolder:      ()          => ipcRenderer.invoke('dialog:select-folder'),
  getDownloadsDir:   ()          => ipcRenderer.invoke('settings:get-downloads-dir'),
  openFolder:        (path) => ipcRenderer.invoke('shell:open-folder', path),
  openFile:          (path) => ipcRenderer.invoke('shell:open-file', path),
  openExternal:      (url)  => ipcRenderer.invoke('shell:open-external', url),
  openExtensionFolder: ()   => ipcRenderer.invoke('extension:open-folder'),
  selectImageFolder: ()     => ipcRenderer.invoke('dialog:select-image-folder'),
  onJobProgress: (cb) => ipcRenderer.on('job-progress', (_e, d) => cb(d)),
  onJobComplete: (cb) => ipcRenderer.on('job-complete', (_e, d) => cb(d)),
  onJobError:    (cb) => ipcRenderer.on('job-error',    (_e, d) => cb(d)),
  removeAllListeners: (ch) => ipcRenderer.removeAllListeners(ch),
  // ── VIRAL VIDEO AI ────────────────────────────────────────────────────────
  viralCreateProxy:  (videoPath) => ipcRenderer.invoke('viral:create-proxy', videoPath),
  viralCutSegment:   (data)      => ipcRenderer.invoke('viral:cut-segment', data),
  // ── AUDIO TO VIDEO ───────────────────────────────────────────────────────
  selectAudioFile: ()       => ipcRenderer.invoke('dialog:select-audio-file'),
  saveTextFile:    (data)   => ipcRenderer.invoke('dialog:save-text-file', data),
  writeTextFile:   (data)   => ipcRenderer.invoke('file:write-text', data),
  prepareAudio:    (filePath) => ipcRenderer.invoke('audio:prepare', filePath),
  extractAudio:    (filePath) => ipcRenderer.invoke('audio:extract', filePath),
  extractAudioChunk: (data)  => ipcRenderer.invoke('audio:extract-chunk', data),
  saveAudioFromVideo:    (data) => ipcRenderer.invoke('video:save-audio', data),
  saveElevenLabsAudio:   (data)      => ipcRenderer.invoke('elevenlabs:save-audio', data),
  elTTS:                 (data)      => ipcRenderer.invoke('elevenlabs:tts', data),
  elScanCredits:         ()          => ipcRenderer.invoke('elevenlabs:scan-credits'),
  elSystemStatus:        ()          => ipcRenderer.invoke('elevenlabs:system-status'),
  elGetVoices:           (userKeys)  => ipcRenderer.invoke('elevenlabs:get-voices', userKeys),
  onElScanProgress:      (cb)        => ipcRenderer.on('el-scan-progress', (_e, done, total) => cb(done, total)),
  elShouldAutoScan:      ()          => ipcRenderer.invoke('elevenlabs:should-auto-scan'),
  elReadKeysFile:        ()          => ipcRenderer.invoke('elevenlabs:read-keys-file'),
  // ── ZALO TTS ────────────────────────────────────────────────────────────────
  zaloCheckKey:          (key)       => ipcRenderer.invoke('zalotts:check-key', key),
  zaloPreview:           (data)      => ipcRenderer.invoke('zalotts:preview', data),
  zaloGenerate:          (data)      => ipcRenderer.invoke('zalotts:generate', data),
  zaloGenerateSRT:       (data)      => ipcRenderer.invoke('zalotts:generate-srt', data),
  onZaloSRTProgress:     (cb)        => ipcRenderer.on('zalo-srt-progress', (_e, data) => cb(data)),
  // ── VIDEO DOWNLOADER (yt-dlp) ────────────────────────────────────────────
  downloaderCheck:         ()      => ipcRenderer.invoke('downloader:check'),
  downloaderSetup:         ()      => ipcRenderer.invoke('downloader:setup'),
  downloaderInfo:          (url)   => ipcRenderer.invoke('downloader:info', url),
  downloaderStart:         (opts)  => ipcRenderer.invoke('downloader:start', opts),
  downloaderCancel:        ()      => ipcRenderer.invoke('downloader:cancel'),
  onDownloaderProgress:    (cb)    => ipcRenderer.on('downloader:progress',       (_e, d) => cb(d)),
  onDownloaderSetupProgress:(cb)   => ipcRenderer.on('downloader:setup-progress', (_e, d) => cb(d)),
  getAppVersion:    ()   => ipcRenderer.invoke('app:get-version'),
  // ── AUTO UPDATER ─────────────────────────────────────────────────────────
  checkUpdate:      ()   => ipcRenderer.invoke('update:check'),
  downloadUpdate:   ()   => ipcRenderer.invoke('update:download'),
  installUpdate:    ()   => ipcRenderer.invoke('update:install'),
  onUpdateAvailable:     (cb) => ipcRenderer.on('update:available',      (_e, info) => cb(info)),
  onUpdateProgress:      (cb) => ipcRenderer.on('update:progress',       (_e, data) => cb(data)),
  onUpdateDownloaded:    (cb) => ipcRenderer.on('update:downloaded',     (_e, data) => cb(data)),
  onUpdateDownloadError: (cb) => ipcRenderer.on('update:download-error', (_e, data) => cb(data)),
});