const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  // ── 3 HÀM BẢO MẬT BẮT BUỘC PHẢI CÓ ────────────────────────────────────────
  getHWID:      ()         => ipcRenderer.invoke('auth:get-hwid'),
  checkLicense: ()         => ipcRenderer.invoke('auth:check-license'),
  activateApp:  (key)      => ipcRenderer.invoke('auth:activate', key),

  // ── VOICES / TTS (TÍNH NĂNG GIỌNG NÓI MỚI) ────────────────────────────────
  geminiTTS:        (data) => ipcRenderer.invoke('gemini:tts', data),
  geminiQuotaStatus:(data) => ipcRenderer.invoke('gemini:quota-status', data),
  geminiTTSSRT:     (data) => ipcRenderer.invoke('gemini:tts-srt', data),
  geminiTranslateSRT:(data)=> ipcRenderer.invoke('gemini:translate-srt', data),
  scanVideoSubtitles:(data)=> ipcRenderer.invoke('video:scan-subtitles', data),
  installEasyOCR:    ()   => ipcRenderer.invoke('ocr:install-easyocr'),
  onOcrInstallProgress: (cb) => ipcRenderer.on('ocr-install-progress', (_e, d) => cb(d)),
  onReviewFilmLog:  (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('review-film-log', w); return w; },
  onGeminiSRTProgress:  (cb) => ipcRenderer.on('gemini-srt-progress', (_e, data) => cb(data)),
  onGeminiSRTLog:       (cb) => ipcRenderer.on('gemini-srt-log', (_e, text) => cb(text)),
  onGeminiTTSProgress:  (cb) => ipcRenderer.on('gemini-tts-progress', (_e, data) => cb(data)),
  onGeminiTTSLog:       (cb) => ipcRenderer.on('gemini-tts-log', (_e, text) => cb(text)),
  getVoices:     ()     => ipcRenderer.invoke('tts:get-voices'),
  generateVoice:    (data) => ipcRenderer.invoke('tts:generate', data),
  generateSRTVoice: (data) => ipcRenderer.invoke('tts:generate-srt', data),
  elTTS_SRT:        (data) => ipcRenderer.invoke('elevenlabs:tts-srt', data),
  onTTSSRTProgress: (cb)   => ipcRenderer.on('tts-srt-progress', (_e, data) => cb(data)),
  onVoiceLog:       (cb)   => ipcRenderer.on('voice-log', (_e, data) => cb(data)),
  previewVoice:  (name) => ipcRenderer.invoke('tts:preview', name), // <--- DÒNG MỚI THÊM

  // ── VIDEO EDITOR (FFMPEG) ─────────────────────────────────────────────────
  cutVideo:        (data) => ipcRenderer.invoke('video:cut', data),
  onVideoLog:      (cb)   => ipcRenderer.on('video-log', (_e, data) => cb(data)),
  readVideoFolder: (path) => ipcRenderer.invoke('video:read-folder', path),
  mergeVideo:      (data) => ipcRenderer.invoke('video:merge', data),
  extractImages:   (data) => ipcRenderer.invoke('video:extract-images', data),
  extractFrame:    (data) => ipcRenderer.invoke('video:extract-frame', data),
  burnSubtitles:   (data) => ipcRenderer.invoke('video:burnSubtitles', data),
  replaceAudio:    (data) => ipcRenderer.invoke('video:replaceAudio', data),
  mixAudio:        (data) => ipcRenderer.invoke('video:mixAudio', data),
  trimLoopVideo:   (data) => ipcRenderer.invoke('video:trim-loop', data),
  mixAudioVideo:   (data) => ipcRenderer.invoke('video:mix-audio', data),
  cutLossless:     (data) => ipcRenderer.invoke('video:cut-lossless', data),
  adjustAudioTempo:(data) => ipcRenderer.invoke('audio:adjust-tempo', data),
  audioSeparate:   (data) => ipcRenderer.invoke('audio:separate', data),
  concatAudio:     (data) => ipcRenderer.invoke('video:concat-audio', data),
  concatWavFiles:  (data) => ipcRenderer.invoke('audio:concat-wavs', data),
  // ── Stock Video (Pexels / Pixabay) ────────────────────────────────────────
  stockVideoSearch:   (p) => ipcRenderer.invoke('stock-video:search', p),
  stockVideoDownload: (p) => ipcRenderer.invoke('stock-video:download', p),
  // ── VEO STUDIO ─────────────────────────────────────────────────
  uploadDnaImage:      (data) => ipcRenderer.invoke('veo:upload-image', data),
  clearUploadCache:    ()     => ipcRenderer.invoke('veo:clear-upload-cache'),
  saveBase64Image: (data) => ipcRenderer.invoke('image:save-base64', data),
  runVeo:         (data) => ipcRenderer.invoke('veo:run', data),
  pauseVeo:       ()     => ipcRenderer.invoke('veo:pause'),
  resumeVeo:      ()     => ipcRenderer.invoke('veo:resume'),
  extendVideo:    (data) => ipcRenderer.invoke('veo:extend', data),
  extendChain:    (data) => ipcRenderer.invoke('veo:extend-chain', data),
  onVeoLog:       (cb)   => { const w = (_e, data) => cb(data); ipcRenderer.on('veo-log', w); return w; },
  offVeoLog:      (w)    => ipcRenderer.removeListener('veo-log', w),
  checkVeoCookie: (cookie) => ipcRenderer.invoke('veo:check-cookie', cookie),
  autoRemoveWatermark: (data) => ipcRenderer.invoke('watermark:auto-remove', data),
  autoCropWatermark:   (data) => ipcRenderer.invoke('watermark:auto-crop', data),
  detectWatermarkOnly: (data) => ipcRenderer.invoke('watermark:detect-only', data),
  onWatermarkLog: (cb) => { const w = (_e, d) => cb(d); ipcRenderer.on('watermark-log', w); return w; },
  videoRecreate:       (data) => ipcRenderer.invoke('video:recreate', data),
  onVideoRecreatLog:   (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('video-recreate-log', w); return w; },
  // ── CÁC HÀM CŨ ────────────────────────────────────────────────────────────
  getJobs:    ()         => ipcRenderer.invoke('db:get-jobs'),
  createJob:  (jobData)  => ipcRenderer.invoke('db:create-job', jobData),
  deleteJob:  (id)       => ipcRenderer.invoke('db:delete-job', id),
  retryJob:   (id)       => ipcRenderer.invoke('db:retry-job',  id),
  countJobs:  (status)   => ipcRenderer.invoke('db:count-jobs', status),
  getConcurrency:  ()        => ipcRenderer.invoke('settings:get-concurrency'),
  setConcurrency:  (value)   => ipcRenderer.invoke('settings:set-concurrency', value),
  getSetting:      (key, dv) => ipcRenderer.invoke('settings:get', key, dv),
  setSetting:      (key, v)  => ipcRenderer.invoke('settings:set', key, v),
  openBrowserLogin:  (profileId) => ipcRenderer.invoke('browser:open-login', profileId),
  checkLogin:        (profileId) => ipcRenderer.invoke('browser:check-login', profileId),
  checkAllLogins:    (ids)       => ipcRenderer.invoke('browser:check-all-logins', ids),
  closeBrowser:      ()          => ipcRenderer.invoke('browser:close'),
  selectFile:        (type)      => ipcRenderer.invoke('dialog:select-file', type),
  selectFolder:      ()          => ipcRenderer.invoke('dialog:select-folder'),
  readImageAsDataUrl: (p)        => ipcRenderer.invoke('read-image-as-dataurl', p),
  getDownloadsDir:   ()          => ipcRenderer.invoke('settings:get-downloads-dir'),
  openFolder:        (path) => ipcRenderer.invoke('shell:open-folder', path),
  openFile:          (path) => ipcRenderer.invoke('shell:open-file', path),
  openExternal:      (url)  => ipcRenderer.invoke('shell:open-external', url),
  openExtensionFolder: ()   => ipcRenderer.invoke('extension:open-folder'),
  labsCheckAuth:       ()   => ipcRenderer.invoke('labs:check-auth'),
  selectImageFolder: ()     => ipcRenderer.invoke('dialog:select-image-folder'),
  onJobProgress: (cb) => ipcRenderer.on('job-progress', (_e, d) => cb(d)),
  onJobComplete: (cb) => ipcRenderer.on('job-complete', (_e, d) => cb(d)),
  onJobError:    (cb) => ipcRenderer.on('job-error',    (_e, d) => cb(d)),
  removeAllListeners: (ch) => ipcRenderer.removeAllListeners(ch),
  removeListener:     (ch, fn) => ipcRenderer.removeListener(ch, fn),
  // ── VIRAL VIDEO AI ────────────────────────────────────────────────────────
  viralCreateProxy:  (videoPath) => ipcRenderer.invoke('viral:create-proxy', videoPath),
  viralCutSegment:   (data)      => ipcRenderer.invoke('viral:cut-segment', data),
  // ── WHISPER LOCAL (main process worker_thread) ──────────────────────────────
  whisperTranscribeChunk: (data) => ipcRenderer.invoke('whisper:transcribe-chunk', data),
  whisperPreloadModel:    ()     => ipcRenderer.invoke('whisper:preload-model'),
  onWhisperProgress:      (cb)   => ipcRenderer.on('whisper:progress', (_e, d) => cb(d)),
  // ── GROQ WHISPER (cloud, nhanh + chính xác hơn) ─────────────────────────────
  groqWhisperChunk: (data) => ipcRenderer.invoke('groq:whisper-chunk', data),
  // ── AUDIO TO VIDEO ───────────────────────────────────────────────────────
  selectAudioFile:     ()   => ipcRenderer.invoke('dialog:select-audio-file'),
  selectMultipleFiles: ()   => ipcRenderer.invoke('dialog:select-multiple-files'),
  saveTextFile:    (data)   => ipcRenderer.invoke('dialog:save-text-file', data),
  writeTextFile:   (data)   => ipcRenderer.invoke('file:write-text', data),
  writeFile:       (data)   => ipcRenderer.invoke('file:write-text', data),
  writeBase64File: (data)   => ipcRenderer.invoke('file:write-base64', data),
  aiStudioConnect:       ()     => ipcRenderer.invoke('aistudio:connect'),
  aiStudioStatus:        ()     => ipcRenderer.invoke('aistudio:status'),
  aiStudioGenerateImage: (data) => ipcRenderer.invoke('aistudio:generate-image', data),
  aiStudioDisconnect:    ()     => ipcRenderer.invoke('aistudio:disconnect'),
  onAiStudioStatus: (cb) => ipcRenderer.on('aistudio:status', (_, msg) => cb(msg)),
  offAiStudioStatus: (cb) => ipcRenderer.removeListener('aistudio:status', cb),
  deleteFile:      (filePath)   => ipcRenderer.invoke('fs:delete-file', filePath),
  renameFile:      (data)       => ipcRenderer.invoke('fs:rename-file', data),
  rvcCheck:        ()           => ipcRenderer.invoke('rvc:check'),
  rvcInstall:      ()           => ipcRenderer.invoke('rvc:install'),
  rvcBrowseModel:  ()           => ipcRenderer.invoke('rvc:browse-model'),
  rvcBrowseIndex:  ()           => ipcRenderer.invoke('rvc:browse-index'),
  createFolder:    (folderPath) => ipcRenderer.invoke('fs:create-folder', folderPath),
  listFiles:       (folderPath) => ipcRenderer.invoke('fs:list-files', folderPath),
  listImagesRecursive: (dir)   => ipcRenderer.invoke('fs:list-images-recursive', dir),
  readTextFile:    (filePath)   => ipcRenderer.invoke('fs:read-text-file', filePath),
  readFileBase64:  (filePath)   => ipcRenderer.invoke('fs:read-file-base64', filePath),
  readFile:        (filePath)   => ipcRenderer.invoke('fs:read-file', filePath),
  compressForUpload: (data)    => ipcRenderer.invoke('video:compress-for-upload', data),
  compressAudioForTranscribe: (data) => ipcRenderer.invoke('audio:compress-for-transcribe', data),
  prepareAudio:    (filePath) => ipcRenderer.invoke('audio:prepare', filePath),
  extractAudio:    (filePath) => ipcRenderer.invoke('audio:extract', filePath),
  extractAudioChunk: (data)  => ipcRenderer.invoke('audio:extract-chunk', data),
  separateVocals:  (data)    => ipcRenderer.invoke('audio:separate-vocals', data),
  deleteTempDir:   (dirPath) => ipcRenderer.invoke('fs:delete-temp-dir', dirPath),
  saveAudioFromVideo:    (data) => ipcRenderer.invoke('video:save-audio', data),
  saveElevenLabsAudio:   (data)      => ipcRenderer.invoke('elevenlabs:save-audio', data),
  elTTS:                 (data)      => ipcRenderer.invoke('elevenlabs:tts', data),
  elCloneVoice:          (data)      => ipcRenderer.invoke('elevenlabs:clone-voice', data),
  elDeleteVoice:         (data)      => ipcRenderer.invoke('elevenlabs:delete-voice', data),
  elScanCredits:         ()          => ipcRenderer.invoke('elevenlabs:scan-credits'),
  elSystemStatus:        ()          => ipcRenderer.invoke('elevenlabs:system-status'),
  elGetVoices:           (userKeys)  => ipcRenderer.invoke('elevenlabs:get-voices', userKeys),
  onElScanProgress:      (cb)        => ipcRenderer.on('el-scan-progress', (_e, done, total) => cb(done, total)),
  elShouldAutoScan:      ()          => ipcRenderer.invoke('elevenlabs:should-auto-scan'),
  elReadKeysFile:        ()          => ipcRenderer.invoke('elevenlabs:read-keys-file'),
  elMergeAudio:          (data)      => ipcRenderer.invoke('elevenlabs:merge-audio', data),
  // ── ZALO TTS ────────────────────────────────────────────────────────────────
  zaloCheckKey:          (key)       => ipcRenderer.invoke('zalotts:check-key', key),
  zaloPreview:           (data)      => ipcRenderer.invoke('zalotts:preview', data),
  zaloGenerate:          (data)      => ipcRenderer.invoke('zalotts:generate', data),
  zaloGenerateSRT:       (data)      => ipcRenderer.invoke('zalotts:generate-srt', data),
  onZaloSRTProgress:     (cb)        => ipcRenderer.on('zalo-srt-progress', (_e, data) => cb(data)),
  // ── VIDEO DOWNLOADER (yt-dlp) ────────────────────────────────────────────
  downloaderCheck:         ()      => ipcRenderer.invoke('downloader:check'),
  downloaderSetup:         ()      => ipcRenderer.invoke('downloader:setup'),
  downloaderInfo:          (url)   => ipcRenderer.invoke('downloader:info', url),
  downloaderStart:         (opts)  => ipcRenderer.invoke('downloader:start', opts),
  downloaderCancel:        ()      => ipcRenderer.invoke('downloader:cancel'),
  onDownloaderProgress:     (cb)   => ipcRenderer.on('downloader:progress',        (_e, d) => cb(d)),
  onDownloaderSetupProgress:(cb)   => ipcRenderer.on('downloader:setup-progress',  (_e, d) => cb(d)),
  downloaderBatchStart:    (items) => ipcRenderer.invoke('downloader:batch-start',  items),
  downloaderBatchCancel:   ()      => ipcRenderer.invoke('downloader:batch-cancel'),
  downloaderBatchPause:    (id)    => ipcRenderer.invoke('downloader:batch-pause',  id),
  downloaderBatchResume:   (item)  => ipcRenderer.invoke('downloader:batch-resume', item),
  onBatchProgress:         (cb)    => ipcRenderer.on('downloader:batch-progress',   (_e, d) => cb(d)),
  // ── BILIBILI SEARCH ──────────────────────────────────────────────────────────
  bilibiliSearch:        (opts) => ipcRenderer.invoke('bilibili:search',        opts),
  bilibiliChannelVideos: (opts) => ipcRenderer.invoke('bilibili:channelVideos', opts),
  bilibiliDownload:      (opts) => ipcRenderer.invoke('bilibili:download',      opts),
  // ── YOUTUBE CHANNEL FETCHER ──────────────────────────────────────────────────
  ytChannelVideos:  (opts) => ipcRenderer.invoke('youtube:channel-videos',  opts),
  ytDownloadBest:   (opts) => ipcRenderer.invoke('youtube:download-best',   opts),
  onYtDownloadProgress: (cb) => ipcRenderer.on('youtube:download-progress', (_e, d) => cb(d)),
  abortYtDownload:  () => ipcRenderer.invoke('youtube:abort-download'),
  updateYtDlp:      () => ipcRenderer.invoke('youtube:update-ytdlp'),
  getAppVersion:         ()   => ipcRenderer.invoke('app:get-version'),
  flowkitGetExtensionPath: () => ipcRenderer.invoke('flowkit:get-extension-path'),
  flowkitStartAgent:       () => ipcRenderer.invoke('flowkit:start-agent'),
  flowkitStopAgent:        () => ipcRenderer.invoke('flowkit:stop-agent'),
  flowkitAgentRunning:     () => ipcRenderer.invoke('flowkit:agent-running'),
  flowkitGetLogs:          () => ipcRenderer.invoke('flowkit:get-logs'),
  flowkitInstallDeps:      () => ipcRenderer.invoke('flowkit:install-deps'),
  flowkitOnLog:            (cb) => ipcRenderer.on('flowkit:log', (_, l) => cb(l)),
  flowkitOnStatus:         (cb) => ipcRenderer.on('flowkit:status', (_, s) => cb(s)),
  flowkitOffLog:           () => ipcRenderer.removeAllListeners('flowkit:log'),
  flowkitOffStatus:        () => ipcRenderer.removeAllListeners('flowkit:status'),
  getSystemGeminiKeys:   ()   => ipcRenderer.invoke('app:get-system-gemini-keys'),
  // ── AUTO UPDATER ─────────────────────────────────────────────────────────
  checkUpdate:      ()   => ipcRenderer.invoke('update:check'),
  downloadUpdate:   ()   => ipcRenderer.invoke('update:download'),
  installUpdate:    ()   => ipcRenderer.invoke('update:install'),
  onUpdateAvailable:     (cb) => ipcRenderer.on('update:available',      (_e, info) => cb(info)),
  onUpdateProgress:      (cb) => ipcRenderer.on('update:progress',       (_e, data) => cb(data)),
  onUpdateDownloaded:    (cb) => ipcRenderer.on('update:downloaded',     (_e, data) => cb(data)),
  onUpdateDownloadError: (cb) => ipcRenderer.on('update:download-error', (_e, data) => cb(data)),
  // ── CHATTERBOX TTS ───────────────────────────────────────────────────────────
  chatterboxCheckStatus: ()    => ipcRenderer.invoke('chatterbox:check-status'),
  chatterboxSetup:     ()      => ipcRenderer.invoke('chatterbox:setup'),
  chatterboxCancelSetup:()     => ipcRenderer.invoke('chatterbox:cancel-setup'),
  chatterboxStart:     ()      => ipcRenderer.invoke('chatterbox:start'),
  chatterboxStop:      ()      => ipcRenderer.invoke('chatterbox:stop'),
  chatterboxSynthesizeSRT: (data) => ipcRenderer.invoke('chatterbox:synthesize-srt', data),
  chatterboxRepair:    ()      => ipcRenderer.invoke('chatterbox:repair'),
  onChatterboxLog:     (cb)    => ipcRenderer.on('chatterbox-log',      (_e, d) => cb(d)),
  onChatterboxProgress:(cb)    => ipcRenderer.on('chatterbox-progress', (_e, d) => cb(d)),
  // ── VIENEU TTS ───────────────────────────────────────────────────────────────
  vieNeuCheckStatus:  ()     => ipcRenderer.invoke('vieneu:check-status'),
  vieNeuGetDir:       ()     => ipcRenderer.invoke('vieneu:get-dir'),
  vieNeuSetDir:       (dir)  => ipcRenderer.invoke('vieneu:set-dir', dir),
  vieNeuFindInstall:  ()     => ipcRenderer.invoke('vieneu:find-install'),
  vieNeuSetup:        ()     => ipcRenderer.invoke('vieneu:setup'),
  vieNeuCancelSetup:  ()     => ipcRenderer.invoke('vieneu:cancel-setup'),
  vieNeuRepairTorch:  ()     => ipcRenderer.invoke('vieneu:repair-torch'),
  vieNeuUpgradeGpu:   ()     => ipcRenderer.invoke('vieneu:upgrade-gpu'),
  onVieNeuRepairLog:  (cb)   => ipcRenderer.on('vieneu:repair-log', (_e, d) => cb(d)),
  vieNeuReset:        ()     => ipcRenderer.invoke('vieneu:reset'),
  vieNeuGetVoices:    ()     => ipcRenderer.invoke('vieneu:get-voices'),
  vieNeuFindSpeechRef:   (data) => ipcRenderer.invoke('vieneu:find-speech-ref', data),
  vieNeuSynthesize:      (data) => ipcRenderer.invoke('vieneu:synthesize', data),
  vieNeuSynthesizeSRT:   (data) => ipcRenderer.invoke('vieneu:synthesize-srt', data),
  vieNeuCancel:          ()     => ipcRenderer.invoke('vieneu:cancel'),
  onVieNeuProgress:      (cb)   => ipcRenderer.on('vieneu-progress',     (_e, d) => cb(d)),
  onVieNeuSRTProgress:   (cb)   => ipcRenderer.on('vieneu-srt-progress', (_e, d) => cb(d)),
  onVieNeuLog:           (cb)   => ipcRenderer.on('vieneu-log',          (_e, d) => cb(d)),
  // ── GPT-SoVITS TTS ───────────────────────────────────────────────────────────
  gptSoVITSGetConfig:    ()     => ipcRenderer.invoke('gptsovits:get-config'),
  gptSoVITSSetUrl:       (url)  => ipcRenderer.invoke('gptsovits:set-url', url),
  gptSoVITSTestConn:     ()     => ipcRenderer.invoke('gptsovits:test-connection'),
  gptSoVITSSaveRef:      (data) => ipcRenderer.invoke('gptsovits:save-ref', data),
  gptSoVITSDeleteRef:    (id)   => ipcRenderer.invoke('gptsovits:delete-ref', id),
  gptSoVITSSynthesize:   (data) => ipcRenderer.invoke('gptsovits:synthesize', data),
  gptSoVITSSynthSRT:     (data) => ipcRenderer.invoke('gptsovits:synthesize-srt', data),
  gptSoVITSCheckInstall: ()     => ipcRenderer.invoke('gptsovits:check-install'),
  gptSoVITSInstall:      (opts) => ipcRenderer.invoke('gptsovits:install', opts),
  gptSoVITSCancelInstall:()     => ipcRenderer.invoke('gptsovits:cancel-install'),
  gptSoVITSSetFolder:    (p)    => ipcRenderer.invoke('gptsovits:set-folder', p),
  gptSoVITSStartServer:  ()     => ipcRenderer.invoke('gptsovits:start-server'),
  gptSoVITSStopServer:   ()     => ipcRenderer.invoke('gptsovits:stop-server'),
  gptSoVITSTranscribe:   (d)    => ipcRenderer.invoke('gptsovits:transcribe', d),
  gptSoVITSSplitRef:       (d)  => ipcRenderer.invoke('gptsovits:split-ref-audio', d),
  gptSoVITSSaveOutputFolder:(f) => ipcRenderer.invoke('gptsovits:save-output-folder', f),
  onGptSoVITSLog:           (cb) => ipcRenderer.on('gptsovits-log',            (_e, d) => cb(d)),
  onGptSoVITSSRTProgress:   (cb) => ipcRenderer.on('gptsovits-srt-progress',   (_e, d) => cb(d)),
  onGptSoVITSSetupProgress: (cb) => ipcRenderer.on('gptsovits-setup-progress', (_e, d) => cb(d)),
  onGptSoVITSServerStopped: (cb) => ipcRenderer.on('gptsovits-server-stopped', (_e, d) => cb(d)),
  // ── KOKORO TTS ───────────────────────────────────────────────────────────────
  kokoroCheckStatus: ()     => ipcRenderer.invoke('kokoro:check-status'),
  kokoroStartServer: ()     => ipcRenderer.invoke('kokoro:start-server'),
  kokoroStopServer:  ()     => ipcRenderer.invoke('kokoro:stop-server'),
  kokoroSynthesize:  (data) => ipcRenderer.invoke('kokoro:synthesize', data),
  onKokoroLog:       (cb)   => ipcRenderer.on('kokoro-log', (_e, d) => cb(d)),
  // ── STORY LOOP ───────────────────────────────────────────────────────────────
  veoGenerateSingle:  (data) => ipcRenderer.invoke('veo:generate-single', data),
  ffmpegLoopVideo:    (data) => ipcRenderer.invoke('ffmpeg:loop-video-for-audio', data),
  concatRandomBg:     (data) => ipcRenderer.invoke('mc:concat-random-bg', data),
  ffmpegCropZoom:     (data) => ipcRenderer.invoke('ffmpeg:crop-zoom', data),
  checkVeoConnection: ()     => ipcRenderer.invoke('veo:check-connection'),
  bgGenerateImage:    (data) => ipcRenderer.invoke('bg:generate-image', data),
  bgGenerateI2V:      (data) => ipcRenderer.invoke('bg:generate-i2v', data),
  scenePrepareVideo:  (data) => ipcRenderer.invoke('scene:prepare-video', data),
  joinDownloadsPath:  (name) => ipcRenderer.invoke('path:join-downloads', name),
  saveImageBytes:     (p, bytes) => ipcRenderer.invoke('fk:save-image-bytes', p, bytes),
  downloadUrl:        (url, p)   => ipcRenderer.invoke('fk:download-url', url, p),
  listDir:            (dir)      => ipcRenderer.invoke('fs:list-dir', dir),
  genViralImage:          (params) => ipcRenderer.invoke('viral:gen-image', params),
  readFileBytesAsBase64:  (p)      => ipcRenderer.invoke('fs:read-base64', p),
  // ── TIKTOK PLAYWRIGHT ──────────────────────────────────────────────────────
  tiktokOpenLogin:     (p)      => ipcRenderer.invoke('tiktok:open-login', p),
  tiktokCheckLogin:    (p)      => ipcRenderer.invoke('tiktok:check-login', p),
  tiktokPostVideo:     (params) => ipcRenderer.invoke('tiktok:post-video', params),
  tiktokFetchProducts: (p)      => ipcRenderer.invoke('tiktok:fetch-products', p),
  onTikTokLog:         (cb) => { const w = (_e, d) => cb(d); ipcRenderer.on('tiktok:log', w); return w; },
  onTikTokProgress:    (cb) => { const w = (_e, d) => cb(d); ipcRenderer.on('tiktok:progress', w); return w; },
  openOutputPath:     (p)    => ipcRenderer.invoke('shell:open-path', p),
  onStoryLoopLog:     (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('storyloop:log', w); return w; },
  // ── STORY PIPELINE ───────────────────────────────────────────────────────────
  storyTTSWithSRT:       (data) => ipcRenderer.invoke('story:tts-with-srt', data),
  onStoryPipelineProgress: (cb) => ipcRenderer.on('story-pipeline:progress', (_e, d) => cb(d)),
  // ── MC STUDIO ────────────────────────────────────────────────────────────────
  mcGenerateClip:     (data) => ipcRenderer.invoke('mc:generate-clip', data),
  mcCompositeVideo:   (data) => ipcRenderer.invoke('mc:composite-video', data),
  onMCStudioLog:      (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('mc-studio:log', w); return () => ipcRenderer.off('mc-studio:log', w); },
  // ── CAPCUT EDITOR ────────────────────────────────────────────────────────────
  capcut_export:        (data) => ipcRenderer.invoke('capcut_export', data),
  getVideoDuration:     (data) => ipcRenderer.invoke('capcut:get-duration', data),
  onCapcutLog:          (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('capcut:log', w); return () => ipcRenderer.off('capcut:log', w); },
  capcutStartServer:    (data) => ipcRenderer.invoke('capcut:start-server', data),
  capcutStopServer:     ()     => ipcRenderer.invoke('capcut:stop-server'),
  capcutServerStatus:   ()     => ipcRenderer.invoke('capcut:server-status'),
  capcutSelectFile:     (data) => ipcRenderer.invoke('capcut:select-file', data),
  onCapcutServerLog:    (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('capcut:server-log', w); return () => ipcRenderer.off('capcut:server-log', w); },

  voicesList:   ()      => ipcRenderer.invoke('voices:list'),
  voicesSave:   (data)  => ipcRenderer.invoke('voices:save', data),
  voicesDelete: (data)  => ipcRenderer.invoke('voices:delete', data),

  // ── REMOTION RENDER ──────────────────────────────────────────────────────
  remotionGetSystemPrompt:  ()          => ipcRenderer.invoke('remotion:get-system-prompt'),
  remotionRenderCode:       (data)      => ipcRenderer.invoke('remotion:render-code', data),
  remotionGetDefaultOutputDir: ()       => ipcRenderer.invoke('remotion:get-default-output-dir'),
  remotionSelectOutputDir:  ()          => ipcRenderer.invoke('remotion:select-output-dir'),
  remotionOpenDir:          (dir)       => ipcRenderer.invoke('remotion:open-dir', dir),
  remotionOpenVideo:            (filePath) => ipcRenderer.invoke('remotion:open-video', filePath),
  remotionSelectSourceVideo:       ()       => ipcRenderer.invoke('remotion:select-source-video'),
  remotionCopyVideoToPublic:       (data)   => ipcRenderer.invoke('remotion:copy-video-to-public', data),
  remotionSelectReferenceFiles:    ()       => ipcRenderer.invoke('remotion:select-reference-files'),
  remotionReadFileBase64:          (fp)     => ipcRenderer.invoke('remotion:read-file-base64', fp),
  remotionUploadToGeminiFileApi:   (data)   => ipcRenderer.invoke('remotion:upload-to-gemini-file-api', data),
  remotionCheckSetup:              ()        => ipcRenderer.invoke('remotion:check-setup'),
  remotionGetPublicDir:            ()        => ipcRenderer.invoke('remotion:get-public-dir'),
  remotionCopyAudioToPublic:       (data)    => ipcRenderer.invoke('remotion:copy-audio-to-public', data),
  remotionCopyRefImagesToPublic:   (data)    => ipcRenderer.invoke('remotion:copy-ref-images-to-public', data),
  onRemotionUploadProgress:        (cb)     => { const w = (_e, d) => cb(d); ipcRenderer.on('remotion:upload-progress', w); return () => ipcRenderer.off('remotion:upload-progress', w); },
  onRemotionSetupLog:              (cb)     => { const w = (_e, d) => cb(d); ipcRenderer.on('remotion:setup-log', w); return () => ipcRenderer.off('remotion:setup-log', w); },
  onRemotionLog:            (cb)        => { const w = (_e, d) => cb(d); ipcRenderer.on('remotion:log', w); return () => ipcRenderer.off('remotion:log', w); },

  // ── AI VIDEO REMIXER ─────────────────────────────────────────────────────
  remixerProbeVideo:      (data) => ipcRenderer.invoke('remixer:probe-video', data),
  remixerGetAudioDuration:(data) => ipcRenderer.invoke('remixer:get-audio-duration', data),
  remixerCutClip:         (data) => ipcRenderer.invoke('remixer:cut-clip', data),
  remixerWritePlan:       (data) => ipcRenderer.invoke('remixer:write-plan', data),
  remixerRender:          (data) => ipcRenderer.invoke('remixer:render', data),
  remixerOpenPreview:     (data) => ipcRenderer.invoke('remixer:open-preview', data),
  remixerGetOutputDir:    ()     => ipcRenderer.invoke('remixer:get-output-dir'),
  onRemixerLog:           (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('remixer:log', w); return () => ipcRenderer.off('remixer:log', w); },
  agentAcquireBroll:      (data) => ipcRenderer.invoke('agent:acquire-broll', data),
  agentFixRenderError:    (data) => ipcRenderer.invoke('agent:fix-render-error', data),
  voicePreview:           (data) => ipcRenderer.invoke('voice:preview', data),
  agentSaveRefImages:     (data) => ipcRenderer.invoke('agent:save-ref-images', data),
  agentFindMusic:         (mood) => ipcRenderer.invoke('agent:find-music', mood),
  agentSaveSynthBgm:      (data) => ipcRenderer.invoke('agent:save-synth-bgm', data),
  copyFileToOutput:       (data) => ipcRenderer.invoke('agent:copy-file-to-output', data),
  mixAudioDucking:        (data) => ipcRenderer.invoke('agent:mix-audio-ducking', data),
  mixSfxList:             (data) => ipcRenderer.invoke('agent:mix-sfx-list', data),
  agentRenderIllustration:(data) => ipcRenderer.invoke('agent:render-illustration', data),
  onIllustrationLog:      (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('agent:illustration-log', w); return () => ipcRenderer.off('agent:illustration-log', w); },
  getRemotionPublicDir:   ()     => ipcRenderer.invoke('remotion:get-public-dir'),
  getSetting:             (key, def) => ipcRenderer.invoke('settings:get', key, def),
  agentRenderThumbnail:   (data) => ipcRenderer.invoke('agent:render-thumbnail', data),
  agentCleanupOutput:     (data) => ipcRenderer.invoke('agent:cleanup-output', data),
  agentCleanRemotionPublic: ()   => ipcRenderer.invoke('agent:clean-remotion-public'),

  // ── EYES CHALLENGE ───────────────────────────────────────────────────────
  eyesChallengeRender:  (data) => ipcRenderer.invoke('eyes:render-video', data),
  onEyesLog:            (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('eyes:log', w); return () => ipcRenderer.off('eyes:log', w); },

  // ── FACEBOOK AUTO POST ────────────────────────────────────────────────────
  fbGetPages:    (data) => ipcRenderer.invoke('fb:get-pages',    data),
  fbDebugToken:  (data) => ipcRenderer.invoke('fb:debug-token',  data),
  fbPostReel:       (data) => ipcRenderer.invoke('fb:post-reel',    data),
  fbPostComment:    (data) => ipcRenderer.invoke('fb:post-comment',  data),
  fbOAuthLogin:     ()     => ipcRenderer.invoke('fb:oauth-login'),
  fbScheduleStatus: (data) => ipcRenderer.send('fb:schedule-status', data),
  onFbLog:       (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('fb:log',      w); return () => ipcRenderer.off('fb:log',      w); },
  onFbProgress:  (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('fb:progress', w); return () => ipcRenderer.off('fb:progress', w); },
  generateAIStudioImage:(data) => ipcRenderer.invoke('aistudio:generate-image', data),
  writeBase64File:      (data) => ipcRenderer.invoke('file:write-base64', data),
  ttsGenerate:          (data) => ipcRenderer.invoke('tts:generate', data),
  findMusic:            (mood) => ipcRenderer.invoke('agent:find-music', mood),
  showItemInFolder:     (p)    => ipcRenderer.invoke('shell:show-item-in-folder', p),

  // ── TRUYỆN MA AUDIO ──────────────────────────────────────────────────────
  horrorProcess:         (data) => ipcRenderer.invoke('horror:process', data),
  horrorCancel:          ()     => ipcRenderer.invoke('horror:cancel'),
  horrorFetchTranscript: (url)  => ipcRenderer.invoke('horror:fetch-transcript', url),
  onHorrorLog:          (cb)   => { const w = (_e, d) => cb(d); ipcRenderer.on('horror-log', w); return () => ipcRenderer.off('horror-log', w); },
  horrorTrimSegment:      (data) => ipcRenderer.invoke('horror:trim-segment', data),
  horrorConcatSegments:   (data) => ipcRenderer.invoke('horror:concat-segments', data),
  horrorExtractFrame:     (data) => ipcRenderer.invoke('horror:extract-frame', data),
  horrorBgExtractFrames:        (data) => ipcRenderer.invoke('horror:bg-extract-frames', data),
  horrorBgExtractVideoFrames:   (data) => ipcRenderer.invoke('horror:bg-extract-video-frames', data),
  horrorBgSaveFrame:            (data) => ipcRenderer.invoke('horror:bg-save-frame', data),
  horrorBgReassemble:           (data) => ipcRenderer.invoke('horror:bg-reassemble', data),
  horrorBgCleanup:              (data) => ipcRenderer.invoke('horror:bg-cleanup', data),
  horrorCleanupCache:      (data) => ipcRenderer.invoke('horror:cleanup-cache', data),
  horrorPreCrop:           (data) => ipcRenderer.invoke('horror:pre-crop', data),
  horrorBgSaveGenerated:   (data) => ipcRenderer.invoke('horror:bg-save-generated', data),
  horrorPreTrim:           (data) => ipcRenderer.invoke('horror:pre-trim', data),
  horrorPitchShift:        (data) => ipcRenderer.invoke('horror:pitch-shift', data),

  // ── HONGGUO (红果短剧) ─────────────────────────────────────────────────
  hongguoGetHome:        ()                      => ipcRenderer.invoke('hongguo:get-home'),
  hongguoGetSeriesInfo:  (seriesId)              => ipcRenderer.invoke('hongguo:get-series-info',    seriesId),
  hongguoGetVideoUrl:    (seriesId, vidId)       => ipcRenderer.invoke('hongguo:get-video-url',      seriesId, vidId),
  hongguoDownloadEpisode:(opts)                  => ipcRenderer.invoke('hongguo:download-episode',   opts),
  onHongguoProgress:     (cb) => { const w = (_e, d) => cb(d); ipcRenderer.on('hongguo:download-progress', w); return () => ipcRenderer.off('hongguo:download-progress', w); },
});